import Vue from 'vue';
import Router from 'vue-router';
Vue.use(Router);
export default new Router({
   routes:[
       {   
           name:'home',
           path:'/',
           component:()=>import('./pages/home.vue'),
           redirect:'/index',
           children:[
               {
                   name:'index',
                   path:'/index',
                   component:()=>import('./pages/index.vue')
               },
               {
                    name:'product',
                    path:'/product/:id',
                    component:()=>import('./pages/product.vue')
               },
               {    
                   name:'detail',
                   path:'/detail/:id',
                   component:()=>import('./pages/detail.vue')
               }
           ]
       },
       {
           name:'login',
           path:'/login',
           component:()=>import("./pages/login.vue")
       },
       {
           name:'order',
           path:'/order',
           component:()=>import('./pages/order.vue'),
           redirect:'/orderConfirm',
           children:[
               {
                   name:'orderConfirm',
                   path:'/orderConfirm',
                   component:()=>import('./pages/orderConfirm.vue')
               },
               {
                   name:'orderPay',
                   path:'/orderPay',
                   component:()=>import('./pages/orderPay.vue')
               },
               {
                   name:'orderList',
                   path:'/orderList',
                   component:()=>import('./pages/orderList.vue')
               }
           ]
       },
       {
           name:'cart',
           path:'/cart',
           component:()=>import('./pages/cart.vue')

       }
   ]
})